### ISSUE TITLE
Connection: unknown character

### ISSUE THREAD

**Issue by yagmikita** [yiisoft/yii2-sphinx#4]
While connecting with the following params:

    'components.sphinx' => [
        'class' => 'yii\db\Connection',
        'dsn' => 'mysql:host=127.0.0.1;port=9306;',
        'username' => 'vbuser',
        'password' => 'DCWDz03b',
    ],

i got:

Next exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /var/www/vb/vendor/yiisoft/yii2/db/Connection.php:324

when trying to use the following params:

    'components.sphinx' => [
        'class' => 'yii\sphinx\Connection',
        'dsn' => 'mysql:host=127.0.0.1;port=9306;',
        'username' => 'vbuser',
        'password' => 'DCWDz03b',
    ],

i got

 PHP Fatal error:  Call to a member function prepare() on null in /var/www/vb/vendor/yiisoft/yii2/db/Command.php on line 153

$ php -v
PHP 5.6.7 (cli) (built: Mar 30 2015 16:49:27) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by klimov-paul** [comment]
Why you attempting to use `yii\db\Connection` while connecting to Sphinx? Have you read a docs?

> PHP Fatal error: Call to a member function prepare() on null in /var/www/vb/vendor/yiisoft/yii2/db/Command.php on line 153

Sinse you have not provided any code to reproduce your problem I cann't help with it. 
All I can tell at current code line 153 at 'yii2/db/Command.php' is actually a doc comment, which can not produce any error anyhow:
https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L153

Unless you provide clear way to reproduce your issue I can not help.

**Comment by yagmikita** [comment]
>> Why you attempting to use yii\db\Connection while connecting to Sphinx?
<< when started using sphinx component, it was in beta mode and didn't work correctly, that's why after a few hours of experiments I found out that 'yii\db\Connection' worked perfectly that time.

Now I am moving my site to a new server where this configuration does not work, so I tried again with a new config, that I've provided in a previous post and got a new error, which I can not understand.

>> Sinse you have not provided any code to reproduce your problem I cann't help with it. 
<< Which part of code could help you in solving this issue ? I thought this is an initialization issue and my code is not involved in it, but config file, part of which i provided here.

**Comment by samdark** [comment]
@yagmikita Sphinx has its own Connection class. Try using it instead of db one.

**Comment by klimov-paul** [comment]
`yii2-sphinx` is covered by unit tests, which are passing successfuly, ensuring all search features are working. So most probably there is something from your side.
Also if you have started from Yii2 beta version, you should consider to upgrage your code to the stable release, including both framework and extension.

**Comment by yagmikita** [comment]
So I used \yii\sphinx\Connection again, but anyway I got the error:

[01-Apr-2015 09:37:55 UTC] PHP Fatal error:  Uncaught exception 'yii\base\InvalidParamException' with message 'Response content must not be an array.' in /var/www/vb/vendor/yiisoft/yii2/web/Response.php:871
Stack trace:
#0 /var/www/vb/vendor/yiisoft/yii2/web/Response.php(318): yii\web\Response->prepare()
#1 /var/www/vb/common/components/MyErrorHandler.php(52): yii\web\Response->send()
#2 /var/www/vb/vendor/yiisoft/yii2/base/ErrorHandler.php(170): common\components\MyErrorHandler->renderException(Object(yii\base\ErrorException))
#3 [internal function]: yii\base\ErrorHandler->handleFatalError()
#4 {main}
  thrown in /var/www/vb/vendor/yiisoft/yii2/web/Response.php on line 871
[01-Apr-2015 09:37:55 UTC] PHP Stack trace:
[01-Apr-2015 09:37:55 UTC] PHP   1. {main}() /var/www/vb/frontend/web/vb.php:0
[01-Apr-2015 09:37:55 UTC] PHP   2. yii\base\Application->run() /var/www/vb/frontend/web/vb.php:19
[01-Apr-2015 09:37:55 UTC] PHP   3. yii\web\Application->handleRequest() /var/www/vb/vendor/yiisoft/yii2/base/Application.php:353
[01-Apr-2015 09:37:55 UTC] PHP   4. yii\base\Module->runAction() /var/www/vb/vendor/yiisoft/yii2/web/Application.php:82
[01-Apr-2015 09:37:55 UTC] PHP   5. yii\base\Controller->runAction() /var/www/vb/vendor/yiisoft/yii2/base/Module.php:423
[01-Apr-2015 09:37:55 UTC] PHP   6. yii\base\InlineAction->runWithParams() /var/www/vb/vendor/yiisoft/yii2/base/Controller.php:147
[01-Apr-2015 09:37:55 UTC] PHP   7. call_user_func_array:{/var/www/vb/vendor/yiisoft/yii2/base/InlineAction.php:54}() /var/www/vb/vendor/yiisoft/yii2/base/InlineAction.php:54
[01-Apr-2015 09:37:55 UTC] PHP   8. api\controllers\ProfileController->actionSearch() /var/www/vb/vendor/yiisoft/yii2/base/InlineAction.php:54
[01-Apr-2015 09:37:55 UTC] PHP   9. common\services\SearchService->search() /var/www/vb/api/controllers/ProfileController.php:232
[01-Apr-2015 09:37:55 UTC] PHP  10. common\services\SearchService->allInner() /var/www/vb/common/services/SearchService.php:20
[01-Apr-2015 09:37:55 UTC] PHP  11. common\services\SearchService->searchInner() /var/www/vb/common/services/SearchService.php:58
[01-Apr-2015 09:37:55 UTC] PHP  12. yii\db\Command->queryAll() /var/www/vb/common/services/SearchService.php:40
[01-Apr-2015 09:37:55 UTC] PHP  13. yii\db\Command->queryInternal() /var/www/vb/vendor/yiisoft/yii2/db/Command.php:318
[01-Apr-2015 09:37:55 UTC] PHP  14. yii\db\Command->prepare() /var/www/vb/vendor/yiisoft/yii2/db/Command.php:403

which leads to not initalized Connection::pdo field here (\yii\db\Command::153):

    public function prepare()
    {
        if ($this->pdoStatement == null) {
            $sql = $this->getSql();
            try {
                $this->pdoStatement = $this->db->pdo->prepare($sql);
            } catch (\Exception $e) {
                $message = $e->getMessage() . "\nFailed to prepare SQL: $sql";
                $errorInfo = $e instanceof \PDOException ? $e->errorInfo : null;
                throw new Exception($message, $errorInfo, (int) $e->getCode(), $e);
            }
        }
    }

after opening \yii\sphinx\Connection I found out that you are missing $this->open(); initialization in \yii\sphinx\Connection::createCommand() as it is in \yii\db\Connection. That is why my code fails.

**Comment by klimov-paul** [comment]
It is clear you are using some unstable version of the 'framework' or 'sphinx' extension or even both.
You need to upgrade your project to the latest stable versions of both!

**Comment by yagmikita** [comment]
Changed composer version of both from "*" to "2.0.*@dev" and it seemed to start working properly, thank you for the advice!
